### ISSUE TITLE
vgmstream-cli make `fatal: not a git repository`

### ISSUE THREAD

**Issue by Pysis868** [vgmstream/vgmstream#464]
The "test" release package doesn't seem to have the cli player I use on MacOS, so I build from code.  I needed the newer version, at most "r1050-2441-gd64c3872", than what is currently in Homebrew, "r1040", to play the BoTW bfstm files under Content > Sound > Resource > Stream.

The formula needs minor tweaks, but after those are made and it makes in the cli subdirectory, it is shows:
```
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C cli vgmstream_cli
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ../src libvgmstream.a
make[2]: `libvgmstream.a' is up to date.
gcc -Wall -Werror=format-security -Wdeclaration-after-statement -Wvla -O3 -DVAR_ARRAYS -I../ext_includes  "-DVERSION=\"`../version.sh`\"" vgmstream_cli.c -L../src -L../ext_libs -lvgmstream  -lm -o vgmstream-cli
fatal: not a git repository (or any of the parent directories): .git
strip vgmstream-cli
```

Making from the project root with the `vgmstream_cli` specific target produces the same result.

While [doc/BUILD.md](../blob/master/doc/BUILD.md) states "Git: optional, to generate version numbers:", it seems to be required by the `version.sh` reference in the sub-Makefile.
The problem here being I cannot build with any src snapshot package downloaded through GitHub's archive codeload feature, because it does not include the git metadata.

I thought this was more of an error, but I do see the build result now, manually and through Homebrew.

I see `Sep  1 2019` in the help text of both of the programs now, which is helpful, but it still hides the code origin level.

Maybe this version specifier could be optionally added by an external source to help streamline the make process, thus truly removing the need for git metadata and executable?

**Comment by bnnm** [comment]
I think it should work now without git, for old versions try overwritting `version.sh` with current file.

**Comment by Pysis868** [comment]
I see you added https://github.com/losnoco/vgmstream/commit/93a3a03fc69fb3600071a1f4fcb9922ca5602a52#diff-a21a3a6a124ddfb8b1a8d7afe50e40f8 for r1050-2466-ga349c26b past my r1050-2441-gd64c3872.  That's nice, but still doesn't allow us to compare the release versions with what we have installed.

**Comment by bnnm** [comment]
Releases without git should have verifiable version.h now. May be irregularly updated though.
